[package]
name = "aeronyx_crypto"
version = "0.1.0"
edition = "2021"

[lib]
name = "aeronyx_crypto"
crate-type = ["staticlib", "cdylib"]

[dependencies]
ed25519-dalek = "1.0.1"
curve25519-dalek = "3.2.1"
x25519-dalek = "1.2.0"
chacha20poly1305 = "0.9.0"
rand = "0.7"
sha2 = "0.9"
hkdf = "0.11"
bs58 = "0.4.0"
